project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  page-navigation: true
  title: "Shuyuan Shen"
  description: "Shuyuan Shen is an Assistant Professor of Political Science and International Relations at Loyola Marymount University."
  site-url: https://www.shuyuanshen.com
  google-analytics: "G-J175W6HZ1T"
  open-graph: true
  twitter-card: true
  search: false

  page-footer:
    left: "© 2026 Shuyuan Shen"
    center: "Political Science · Loyola Marymount University"
    right: "Built with [Quarto](https://quarto.org/)"

  navbar:
    background: light
    left:
      - href: index.qmd
        text: About

      - href: research/index.qmd
        text: Research

      - href: teaching/index.qmd
        text: Teaching
      
      - href: CV/index.qmd
        text: CV
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true

